### ISSUE TITLE
第一章存在内容缺失

### ISSUE THREAD

**Issue by Spico197** [usyiyi/nlp-py-2e-zh#1]
您好，感谢您的翻译工作。

对比[第一章](https://usyiyi.github.io/nlp-py-2e-zh/1.html)的内容和 [原书](http://www.nltk.org/book/ch01.html#ex-set-comprehension-python)内容发现，第一章`5.1`及之后的内容并未被翻译和添加。

请问是否有后续翻译计划？如果可能的话，是否可以参与翻译和完善？

**Comment by yiwanzi** [comment]
参考这个最新版本：https://yiyibooks.cn/yiyi/nltk_python/ch01.html
